version: '3.5'
services:
    go-environment:
        container_name: go
        image: golang
        command: > 
            bash -c "while ! [ -f "/startup/startup.sh" ];
                do
                    echo "#"
                    sleep 1
                done
                cp /startup/startup.sh /startup.sh
                chmod +x /startup.sh
                /startup.sh
                sleep infinity"
        depends_on:
            - godatabase
        volumes:
            - ./config/go/pkg:/go
            - ./config/go/:/startup:ro
        ports:
            - 80:80
    godatabase:
        container_name: godatabase
        image: mysql
        restart: always
        # After the first run, comment out the lines below
        environment:
             MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
             MYSQL_DATABASE: MYSQL_DATABASE
             MYSQL_USER: MYSQL_USER
             MYSQL_PASSWORD: MYSQL_PASSWORD
        # After the first run, comment out the lines above
        volumes:
          - ./config/data:/var/lib/mysql
    # go-phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   ports:
    #       - '8080:80'
    #   restart: always
    #   environment:
    #       PMA_HOST: godatabase
    #   depends_on:
    #       - godatabase

