version: '3.5'
services:
    go-environment:
        container_name: go
        image: golang
        restart: always
        command: > 
            bash -c "while ! [ -f "/go/Caution-Scheduling/main.go" ];
                do
                    echo "#"
                    sleep 1
                done
                go install github.com/cosmtrek/air@latest
                cd /go/Caution-Scheduling/
                air&
                sleep infinity"
        depends_on:
            - godatabase
        volumes:
            - ./src/:/go/Caution-Scheduling/
        ports:
            - 80:80
    godatabase:
        container_name: godatabase
        image: mysql
        restart: always
        # After the first run, comment out the lines below
        environment:
             MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
             MYSQL_DATABASE: MYSQL_DATABASE
             MYSQL_USER: MYSQL_USER
             MYSQL_PASSWORD: MYSQL_PASSWORD
        # After the first run, comment out the lines above
        volumes:
          - ./config/data:/var/lib/mysql

